"""empty message

Revision ID: 40ec4ed5fc91
Revises: 
Create Date: 2020-10-02 16:22:23.462517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ec4ed5fc91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prenotazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('telefono', sa.String(length=120), nullable=False),
    sa.Column('provincia', sa.String(length=30), nullable=True),
    sa.Column('arrivo', sa.DateTime(), nullable=False),
    sa.Column('durata', sa.Integer(), nullable=False),
    sa.Column('partenza', sa.DateTime(), nullable=False),
    sa.Column('posti', sa.Integer(), nullable=False),
    sa.Column('responsabile', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('gestione', sa.Boolean(), nullable=False),
    sa.Column('cane', sa.Boolean(), nullable=False),
    sa.Column('colore', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prenotazione_nome'), 'prenotazione', ['nome'], unique=False)
    op.create_index(op.f('ix_prenotazione_telefono'), 'prenotazione', ['telefono'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prenotazione_telefono'), table_name='prenotazione')
    op.drop_index(op.f('ix_prenotazione_nome'), table_name='prenotazione')
    op.drop_table('prenotazione')
    # ### end Alembic commands ###
