"""empty message

Revision ID: 8eea39c6b00a
Revises: 40ec4ed5fc91
Create Date: 2020-10-02 17:42:47.594665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8eea39c6b00a'
down_revision = '40ec4ed5fc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prenotazione', 'posti',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prenotazione', 'posti',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
