"""empty message

Revision ID: 324781c59c53
Revises: af0220d31334
Create Date: 2019-12-01 20:32:22.926575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324781c59c53'
down_revision = 'af0220d31334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prenotazione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=120), nullable=True),
    sa.Column('provincia', sa.String(length=2), nullable=True),
    sa.Column('arrivo', sa.DateTime(), nullable=False),
    sa.Column('durata', sa.Integer(), nullable=False),
    sa.Column('posti', sa.Integer(), nullable=False),
    sa.Column('responsabile', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('gestori', sa.Boolean(), nullable=False),
    sa.Column('cane', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prenotazione_nome'), 'prenotazione', ['nome'], unique=False)
    op.create_index(op.f('ix_prenotazione_telefono'), 'prenotazione', ['telefono'], unique=False)
    op.create_table('utente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utente_username'), 'utente', ['username'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_index(op.f('ix_utente_username'), table_name='utente')
    op.drop_table('utente')
    op.drop_index(op.f('ix_prenotazione_telefono'), table_name='prenotazione')
    op.drop_index(op.f('ix_prenotazione_nome'), table_name='prenotazione')
    op.drop_table('prenotazione')
    # ### end Alembic commands ###
